apiVersion: v1
kind: Schema
metadata:
  name: wool-pickup-tracker-schema
  version: "1.0.0"

collections:
  clients:
    description: Farm client contact information
    fields:
      id:
        type: string
        required: true
        description: Unique client identifier
      name:
        type: string
        required: true
        description: Farm/business name
      contactName:
        type: string
        required: true
        description: Primary contact person
      phone:
        type: string
        required: true
        pattern: "^\\+?[1-9]\\d{1,14}$"
        description: Contact phone number
      email:
        type: string
        required: false
        pattern: "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$"
        description: Contact email address
      address:
        type: string
        required: true
        description: Farm physical address
      region:
        type: string
        required: true
        enum: ["Mallee", "Riverland", "Mid North", "Adelaide Hills", "Eyre Peninsula"]
        description: Geographic region
      notes:
        type: string
        required: false
        description: Additional client notes
      createdAt:
        type: timestamp
        required: true
        description: Record creation time
      updatedAt:
        type: timestamp
        required: true
        description: Last update time

  pickups:
    description: Wool pickup records
    fields:
      id:
        type: string
        required: true
        description: Unique pickup identifier
      clientId:
        type: string
        required: true
        description: Reference to client
      driverId:
        type: string
        required: true
        description: Driver user ID
      timestamp:
        type: timestamp
        required: true
        description: Pickup date and time
      location:
        type: object
        required: true
        properties:
          lat:
            type: number
            required: true
            description: GPS latitude
          lng:
            type: number
            required: true
            description: GPS longitude
          address:
            type: string
            required: false
            description: Human-readable address
      wool:
        type: object
        required: true
        properties:
          grade:
            type: string
            required: true
            enum: ["Premium", "Good", "Average", "Lower"]
            description: Wool quality grade
          quantity:
            type: number
            required: true
            minimum: 0
            description: Amount of wool
          unit:
            type: string
            required: true
            enum: ["kg", "bales"]
            description: Unit of measurement
      photos:
        type: array
        required: false
        items:
          type: string
        description: Photo URLs
      notes:
        type: string
        required: false
        description: Additional pickup notes
      status:
        type: string
        required: true
        enum: ["pending", "completed", "cancelled"]
        default: "pending"
        description: Pickup status
      createdAt:
        type: timestamp
        required: true
        description: Record creation time
      updatedAt:
        type: timestamp
        required: true
        description: Last update time

  users:
    description: User profile information
    fields:
      id:
        type: string
        required: true
        description: User identifier (Auth UID)
      email:
        type: string
        required: true
        description: User email address
      displayName:
        type: string
        required: true
        description: User display name
      role:
        type: string
        required: true
        enum: ["driver", "admin", "manager"]
        default: "driver"
        description: User access level
      isActive:
        type: boolean
        required: true
        default: true
        description: Account status
      lastLoginAt:
        type: timestamp
        required: false
        description: Last login time
      createdAt:
        type: timestamp
        required: true
        description: Account creation time

indexes:
  - collection: pickups
    fields: [clientId, timestamp]
    order: [asc, desc]
  - collection: pickups
    fields: [driverId, timestamp]
    order: [asc, desc]
  - collection: pickups
    fields: [status, timestamp]
    order: [asc, desc]
  - collection: clients
    fields: [region, name]
    order: [asc, asc]