name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cache build outputs
      uses: actions/cache@v4
      with:
        path: |
          dist
          node_modules/.vite
        key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}-${{ hashFiles('src/**/*') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}-
          ${{ runner.os }}-build-
    - run: npm ci
    - run: npm run lint
    - run: npm run test:run
    - run: npm run build:ci