name: Deploy to Firebase Hosting (Development)

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:run

      - name: Run linting
        run: npm run lint

      - name: Build project
        run: npm run build
        env:
          # Use development environment variables
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY_DEV }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN_DEV }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID_DEV }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET_DEV }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID_DEV }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID_DEV }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create Firebase Service Account Key File
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}' > $HOME/firebase-service-account-dev.json

      - name: Deploy to Firebase Hosting (Development)
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account-dev.json
          firebase deploy --only hosting --project ${{ secrets.VITE_FIREBASE_PROJECT_ID_DEV }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_DEV }}